version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
  devbox-healthcheck:
    image: curlimages/curl:7.88.1
    command: ["sleep", "infinity"]
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
