name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      app:
        build: .
        env:
          AI_URL: ${{ secrets.AI_URL }}
          AI_KEY: ${{ secrets.AI_KEY }}
          VECTORSTORE__CONNECTION_STRING: ${{ secrets.VECTORSTORE_DSN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          export AI_URL=$AI_URL
          export AI_KEY=$AI_KEY
          docker compose up --build -d
          pytest -q
        env:
          AI_URL: ${{ secrets.AI_URL }}
          AI_KEY: ${{ secrets.AI_KEY }}
          VECTORSTORE__CONNECTION_STRING: ${{ secrets.VECTORSTORE_DSN }}
